### ISSUE TITLE
Wrong version of container images in Kubernetes installation with Helm

### ISSUE THREAD

**Issue by m-dilorenzi** [instana/opentelemetry-demo#2]
# Wrong version of container images

Following the installation instructions for kubernetes and helm chart shown [here](https://github.com/instana/opentelemetry-demo/blob/main/instana/deploy-build.md), all the pods with custom images remains pending because they're not able to pull the 1.4.0 version of the image from the styblope/otel-demo registry. 1.4.0 is the current version of the opentelemetry-demo official project of OpenTelemetry.

## Actual behavior
Pods remain in pending state due to the impossibility to pull the 1.4.0 version of the container images.

## Expected behavior
Pods running with 1.3.1 image version specified in the .env file.

# Actual Solution
Specify the desired version (1.3.1, as in the .env file) in the values-instana-agent.yaml file in the default.image.tag field.

**Comment by styblope** [comment]
This will be fixed soon after we merge and test the recent 1.4 release. Because our demo is a fork of the upstream version we need to catch up on the upstream changes plus make sure our own mods merge without conflicts and everything plays well in Instana.
