### ISSUE TITLE
Unable to see the Website EUM Javascript metrics in Instana dashboard with Kubernetes Helm Chart installation

### ISSUE THREAD

**Issue by m-dilorenzi** [instana/opentelemetry-demo#3]
# Bug Report

After fill the INSTANA_EUM_URL and INSTANA_EUM_KEY fields in the values-instana-agent.yaml file with the URL and key shown in the script of "Add website" section in Instana, no data are visible in the website dashboard. I've used the kubernetes installation with the helm chart and port-forwarding to reach the OTelDemo webpage.

## Actual behavior
No data about the webpage navigation are visible in the website dashboard.

## Expected behavior
Website data shown in the website dashboard.

**Comment by m-dilorenzi** [comment]
Are you able to see the informations in the website dashboard?

I think the issue is in the script source definition. In the fronentd service the source of the script is specified as the following:
![image](https://github.com/instana/opentelemetry-demo/assets/52289654/7317c0bd-0d8e-49d8-a38b-73370dd1657e)

In the Instana sandbox we use for testing, if we want to monitor website the script has the following source
![image](https://github.com/instana/opentelemetry-demo/assets/52289654/1dee0f96-5552-4963-af60-1bac3112987e)
that doesn't contain the reportingURL specified in the configuration file with the key.

Could this be the problem?

**Comment by styblope** [comment]
oh I see what you mean:
```diff
<script>
...
+ ineum('reportingUrl', 'https://eum-orange-saas.instana.io');
- ineum('reportingUrl', 'https://instana.tec.cz.ibm.com:446/eum/');
...
+ <script defer crossorigin="anonymous" src="https://eum.instana.io/eum.min.js"></script>
- <script defer crossorigin="anonymous" src="https://instana.tec.cz.ibm.com:446/eum/eum.min.js"></script>
```
red color is on-prem, green is SaaS

I've really only tested it with a self-hosted instance only, which does work fine. It looks like adding the trailing `/` should do it for SaaS as the javascript is available under https://eum-orange-saas.instana.io/eum.min.js.

**Comment by m-dilorenzi** [comment]
Got it, it works! Thank you for your help, issue closed. 👍
